source 'https://rubygems.org'

gem "animation", "~> 0.1.alpha.3"   # Not required in Compass 0.13+ (https://github.com/ericam/compass-animation)
gem "sass-globbing", "~> 1.0.0"     # Not required for Rails 3.1+
gem "susy", "~> 1.0.9"

gem 'sass', '3.3.0.alpha.149'
gem 'compass', '0.12.2'